// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAogfaV7rQtRETMpg5NH1ekCOVYxVV0GfM',
    appId: '1:60270748521:android:483e51f9d6ffea173813f8',
    messagingSenderId: '60270748521',
    projectId: 'mini-whatsapp-cca48',
    storageBucket: 'mini-whatsapp-cca48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBqtjq9BBSnBKhIOmah_A2U6bSW76pDI',
    appId: '1:60270748521:ios:c84961fca479be943813f8',
    messagingSenderId: '60270748521',
    projectId: 'mini-whatsapp-cca48',
    storageBucket: 'mini-whatsapp-cca48.appspot.com',
    iosBundleId: 'com.example.miniwhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUsLuOWrAZ1Ovqr-of9TdJ9jifMRjum1M',
    appId: '1:60270748521:web:346907f0f330b6473813f8',
    messagingSenderId: '60270748521',
    projectId: 'mini-whatsapp-cca48',
    authDomain: 'mini-whatsapp-cca48.firebaseapp.com',
    storageBucket: 'mini-whatsapp-cca48.appspot.com',
  );
}
